# Example 8
#
# Pulling out all the stops with cluster of seven Vagrant boxes.
#

hosts = {
    "ubuntu" => {
    "box" => "precise64",
    "url" => "http://files.vagrantup.com/precise64.box",
    "ip" => "192.168.33.101"
  },
  "debian" => {
    "box" => "debian7",
    "url" => "http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210-nocm.box",
    "ip" => "192.168.33.102"
  },
  "centos" => {
    "box" => "centos6",
    "url" => "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box",
    "ip" => "192.168.33.103"
  }
}

Vagrant.configure("2") do |config|
  hosts.each do |name, options|
    config.vm.define name do |machine|
      machine.vm.box = options['box']
      machine.vm.box_url = options['url']
      machine.vm.hostname = "%s" % name
      machine.vm.network :private_network, ip: options['ip']

      machine.vm.synced_folder "%s/" % name, "/home/vagrant", create: true, mount_options: ["dmode=777","fmode=666"]

      machine.vm.provider "virtualbox" do |v|
        v.name = name
        v.memory = 256
      end
    end
  end
end
